### ISSUE TITLE
Loris

### ISSUE THREAD

**Issue by nadar** [driftphp/awesome-reactphp#4]
Hi,

We have made a very small react php based api toolkit i would like to post on your list:

https://packagist.org/packages/heartbeat/loris

I was unsure which categories might suit your list best, so i thought to create an issue first.

**Comment by mmoreram** [comment]
@nadar sure!

What about a new category called Projects & Other?

Feel free to create a PR :)

**Comment by nadar** [comment]
Maybe its more like a "mico framework"?

**Comment by nadar** [comment]
I have added a PR

**Comment by mmoreram** [comment]
Merged @nadar, thanks!
